name: habit_tracker
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: 1.0.5
  provider: ^6.1.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.13
  flutter_slidable: ^3.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
